const ICON_PATH = '../assets/icons/';

export const icons = {
  home: require(`${ICON_PATH}home.png`),
  companies: require(`${ICON_PATH}companies.png`),
  financialreports: require(`${ICON_PATH}financialreports.png`),
  streamer: require(`${ICON_PATH}streamer.png`),
  more: require(`${ICON_PATH}more.png`),
  BackArrow: require(`${ICON_PATH}Backarrow.png`),
  Logo: require(`${ICON_PATH}Logo.png`),
  password: require(`${ICON_PATH}password.png`),
  email: require(`${ICON_PATH}email.png`),
  Apple: require(`${ICON_PATH}Apple.png`),
  Facebook: require(`${ICON_PATH}Facebook.png`),
  Gmail: require(`${ICON_PATH}Gmail.png`),
  Search: require(`${ICON_PATH}Search.png`),
  chart: require(`${ICON_PATH}chart.png`),
  newsimage: require(`${ICON_PATH}newsimage.png`),
  timewhite: require(`${ICON_PATH}timewhite.png`),
  likewhite: require(`${ICON_PATH}likewhite.png`),
  messagewhite: require(`${ICON_PATH}messagewhite.png`),
  uploadwhite: require(`${ICON_PATH}uploadwhite.png`),
  newssmallimages1: require(`${ICON_PATH}newssmallimages1.png`),
  newssmallimages2: require(`${ICON_PATH}newssmallimages2.png`),
  User: require(`${ICON_PATH}User.png`),
  Amount: require(`${ICON_PATH}Amount.png`),
  flagicon: require(`${ICON_PATH}flagicon.png`),
  companiesorange: require(`${ICON_PATH}companiesorange.png`),
  settingorange: require(`${ICON_PATH}settingorange.png`),
  userorange: require(`${ICON_PATH}userorange.png`),
  calendarorange: require(`${ICON_PATH}calendarorange.png`),
  chartorange: require(`${ICON_PATH}chartorange.png`),
  eyeorange: require(`${ICON_PATH}eyeorange.png`),
  heartorange: require(`${ICON_PATH}heartorange.png`),
  bulborange: require(`${ICON_PATH}bulborange.png`),
};
